# Generated by Django 5.0 on 2023-12-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terraria_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="planta",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="planta/"),
        ),
    ]
