# Generated by Django 5.0 on 2023-12-07 19:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terraria_app", "0002_planta_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="respuestacuidado",
            name="fecha",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
