# Generated by Django 5.0 on 2023-12-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terraria_app", "0003_respuestacuidado_fecha"),
    ]

    operations = [
        migrations.AddField(
            model_name="respuestacuidado",
            name="estado",
            field=models.CharField(
                choices=[
                    ("ABIERTO", "Abierto"),
                    ("EN_PROGRESO", "En Progreso"),
                    ("COMPLETADO", "Completado"),
                ],
                default="ABIERTO",
                max_length=12,
            ),
        ),
    ]
