# Generated by Django 5.0 on 2023-12-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terraria_app", "0004_respuestacuidado_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="respuestacuidado",
            name="respuesta",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
